# Generated by Django 4.2.7 on 2023-11-18 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('distance_base_price', models.FloatField()),
                ('distance_additional_price', models.FloatField()),
                ('time_multiplier_factor', models.FloatField()),
                ('waiting_charges', models.FloatField()),
                ('additional_distance_limit', models.FloatField(default=0)),
                ('additional_price_after_limit', models.FloatField(default=0)),
                ('max_time_tier1', models.FloatField(default=0)),
                ('max_time_tier2', models.FloatField(default=0)),
                ('max_time_tier3', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
