# Generated by Django 4.2.7 on 2023-11-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingconfig',
            old_name='is_active',
            new_name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='additional_distance_limit',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='additional_price_after_limit',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_time_tier1',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_time_tier2',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='max_time_tier3',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_additional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='distance_base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='waiting_charges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
