# Generated by Django 4.2.7 on 2023-11-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v2', '0002_rename_is_active_pricingconfig_is_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='time_multiplier_factors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
