# Generated by Django 4.2.7 on 2023-11-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing_v2', '0003_remove_pricingconfig_time_multiplier_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
