# Generated by Django 4.2.7 on 2023-11-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v2', '0004_pricingconfig_created_at_pricingconfig_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='time_multiplier_factors',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
