# Generated by Django 4.2.7 on 2023-11-19 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricing_v2', '0005_remove_pricingconfig_time_multiplier_factors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='base_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='monday',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
        ),
        migrations.CreateModel(
            name='TimeMultiplicationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_multiplier_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
            field=models.ManyToManyField(to='pricing_v2.timemultiplicationfactor'),
        ),
    ]
