# Generated by Django 4.2.7 on 2023-11-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v2', '0006_remove_pricingconfig_day_of_week_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='time_multiplier_factor',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='friday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='saturday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='sunday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='thursday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='tuesday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='wednesday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='monday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
