# Generated by Django 4.2.7 on 2023-11-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v2', '0007_remove_pricingconfig_time_multiplier_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='time_multiplication_factor',
            field=models.ManyToManyField(to='pricing_v2.timemultiplicationfactor'),
        ),
    ]
