# Generated by Django 4.2.7 on 2023-11-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing_v2', '0008_pricingconfig_time_multiplication_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfig',
            name='free_waiting_minutes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
